spring:
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:mem:simple-jpa-data-web
    username: sa
    password:
    driverClassName=: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  main:
    banner-mode: log
logging:
  level:
    root: info
    org.hibernate: info
server:
  port: 8080