spring:
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:mem:simple-jpa-data-web;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=FALSE;IGNORECASE=FALSE
    username: sa
    password:
    driverClassName=: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
  main:
    banner-mode: log
logging:
  level:
    root: info
    org.hibernate: info
server:
  port: 8080