com:
  github:
    dnvriend:
      greeter:
        userName: "Dennis"
        messages:
          morningMessage: "Morning %s!"
          afternoonMessage: "Afternoon %s!"
          eveningMessage: "Evening %s!"
          nightMessage: "'Night %s!"
