com:
  github:
    dnvriend:
      greeter:
        userName: "Dennis"
        morningMessage: "Morning %s!"
        afternoonMessage: "Afternoon %s!"
        eveningMessage: "Evening %s!"
        nightMessage: "'Night %s!"
