spring:
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:mem:simple-jpa-data-web
    username: sa
    password:
    driverClassName=: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
  main:
    banner-mode: log

  flyway:
    enabled: true
    locations: "classpath:db/migration/{vendor}"
    checkLocation: true
  level:
    root: info
    org.hibernate: info
    org.flyway: info
server:
  port: 8080

