#my.value: There!
my.week: TUESDAY
my.number: 24
my.active: true
my.names: foo,bar,baz

# props
my.props.name: Dennis
my.props.age: 42

logging.level:
  root: error
  com.github.dnvriend: info

spring:
  main:
    banner-mode: 'off'
    log-startup-info: false
