spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  main:
    banner-mode: log
logging:
  level:
    root: info
    org.hibernate: info
server:
  port: 8080