spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    enabled: true
    locations: "classpath:db/migration/{vendor}"
    check-location: false
    baseline-on-migrate: true