spring:
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName=: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: "classpath:db/migration/{vendor}"
    check-location: false
    baseline-on-migrate: true